markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://flyyoung.github.com
author: flyoung
pygments: true
safe: true
paginate: 16
auto: true
name:flyoung's blog
blogurl:http://www.flyoung.me
description:flyoung occasionally writes about things.

